### ISSUE TITLE
Thanks gregsaun

### ISSUE THREAD

**Issue by zagarolo** [gregsaun/prusa_i3_bear_upgrade#10]
![15096293597262651887560384402895](https://user-images.githubusercontent.com/6859327/32328428-44b2e054-bfda-11e7-9051-4da8d4e12463.jpg)
![15096294160363624466170430965206](https://user-images.githubusercontent.com/6859327/32328491-6e71315c-bfda-11e7-961a-a4da17585bc0.jpg)
![15096294666144085111041558965777](https://user-images.githubusercontent.com/6859327/32328520-7f9d6c16-bfda-11e7-8cb2-ef32121f17a6.jpg)
![1509629505350713018524024116273](https://user-images.githubusercontent.com/6859327/32328549-94cbe4c8-bfda-11e7-8307-d320ad13a373.jpg)

**Comment by gregsaun** [comment]
:heart_eyes:

So good to see this in real!

y_rod_holder will be fixed in priority

**Comment by zagarolo** [comment]
look at my side printing to see it's a bit misaligned or Z wobling you have a tip

**Comment by gregsaun** [comment]
Did you re-calibrate the printer (calibrate xyz)? Did you check your Z level again?

**Comment by zagarolo** [comment]
yes, lined XYZ I did not re-align Z axis again

**Comment by gregsaun** [comment]
This might comes from the y_rod_holder too. Let's fix this first.

**Comment by zagarolo** [comment]
Ok

**Comment by FischOderAal** [comment]
This looks great. Congrats!

**Comment by zagarolo** [comment]
Thanks

**Comment by gregsaun** [comment]
New rod_holder available :)

**Comment by zagarolo** [comment]
![15098946065996616351363590794618](https://user-images.githubusercontent.com/6859327/32416105-d65ea266-c243-11e7-8f0b-e1f7d352a424.jpg)
![15098946872413595762276770128978](https://user-images.githubusercontent.com/6859327/32416117-0d02e08e-c244-11e7-9cdb-254aa09eedf6.jpg)

**Comment by gregsaun** [comment]
yip yip :)

Do you speak Italian? I understand a little bit so you can write in italian and I will answer in english. (my mother tongue is french and I understand a very little bit of german as well)

**Comment by zagarolo** [comment]
Ciao si sono italiano

**Comment by zagarolo** [comment]
Ho visto che hai modificato rod holder oggi stampare e proverò

**Comment by gregsaun** [comment]
I have seen the "quasar vetri" in your picture ;)

Nice. Do you have another spool of orange? :grin:

**Comment by zagarolo** [comment]
Siii bello ho finito ultima bobbina ,,😯😩

**Comment by zagarolo** [comment]
![15098961886463040717652986505756](https://user-images.githubusercontent.com/6859327/32416304-8050125c-c247-11e7-8162-743222399e41.jpg)
E finita 😰😰😰😭😭😭😭

**Comment by gregsaun** [comment]
In case of I am using MF-PETG Neon Orange from extrudr.eu which is very very close to Prusa orange.
https://extrudr.eu/collections/petg/products/extrudr-mf-petg-neon-orange

**Comment by zagarolo** [comment]
Si Colere molto vicino a Prusa

**Comment by gregsaun** [comment]
I have added feet. For now, they have same shape than MK2(s), like this you can reuse your (home made) dampers

**Comment by gregsaun** [comment]
I finished first build yesterday, the black corner on aluminum plate very makes the build very hard to square/tight. After several test on how we can square them correctly I have decided to remove them. Did you use them?

**Comment by zagarolo** [comment]
![15102264444538456475438707170023](https://user-images.githubusercontent.com/6859327/32603000-85348150-c548-11e7-93af-18908cf1a93e.jpg)
![15102264718101468472399496985579](https://user-images.githubusercontent.com/6859327/32603005-882d4e3c-c548-11e7-978c-ba1b7f10bf06.jpg)
![15102265663133439610586895058707](https://user-images.githubusercontent.com/6859327/32603077-b9349846-c548-11e7-831f-4d1999be835e.jpg)
![15102266000083775898046533736153](https://user-images.githubusercontent.com/6859327/32603097-ca31f738-c548-11e7-8e05-6b148442e1a5.jpg)

**Comment by zagarolo** [comment]
ciao ordinato  MF-PETG Neon Orange  e stampato tutto cosa ti riferisci black corner on aluminum plate yes 

come nel tuo progetto la parte del motore installati in basso e la parte anteriore cioe lcd  installati in alto per non avere problemi con il carrello si bloccava

**Comment by zagarolo** [comment]
Hello ordered MF-PETG Neon Orange and printed everything you say black corner on aluminum plate yes

as in your project the part of the engine installed at the bottom and the front ie lcd installed up to not have problems with the car locked

**Comment by gregsaun** [comment]
Ok thank you, I will still remove them, easier and cheaper and does not impact rigidity.

For MF-PETG Neon Orange I print at 225°C and 80°C for bed. Fan I am still testing but at 30-50 for now...

**Comment by zagarolo** [comment]
MF-PETG 240  for bed 90 is perfect linear

**Comment by zagarolo** [comment]
Manufacturer datasheet is 240 bed 90

**Comment by gregsaun** [comment]
Where did you get the datasheet, on their website is 205 and 80? https://extrudr.eu/collections/petg/products/extrudr-mf-petg-neon-orange

**Comment by zagarolo** [comment]
https://www.3djake.it/extrudr/filamento-mf-petg-neon-arancione

**Comment by zagarolo** [comment]
Cosa sono queste righe più grande durante la stampa ? I puoi aiutare  
![img_20171109_141207](https://user-images.githubusercontent.com/6859327/32607253-92effa3a-c558-11e7-9316-1c2db638e79b.jpg)

**Comment by zagarolo** [comment]
ABS 
![img_20171109_141838](https://user-images.githubusercontent.com/6859327/32607352-fa7b9efc-c558-11e7-83ad-839e1568713e.jpg)

**Comment by gregsaun** [comment]
Thanks for the link, interesting!

This is due to the fact it is doing parts of the line, then go somewhere else and then finish the started ones. Then you have this joining line. I do not know how to solve it but some things you can check : 
- layer height
- extruder calibration (over extrusion?)
- extruder temp?

**Comment by zagarolo** [comment]
All parts orange neon petg
![img_20171117_142202](https://user-images.githubusercontent.com/6859327/32949487-4c041452-cba3-11e7-97c8-d997d6ea06ad.jpg)

**Comment by gregsaun** [comment]
Sweet build! In case of I updated the lcd supports to avoid colliding to with rod holders.

Do you still have the wobbling from the previous version?

**Comment by zagarolo** [comment]
![15109256732501755413970560156736](https://user-images.githubusercontent.com/6859327/32949841-848890c2-cba4-11e7-9a47-9be976e4d2d8.jpg)
Hello no wobbling

**Comment by zagarolo** [comment]
![15109258116317727043901309410241](https://user-images.githubusercontent.com/6859327/32949928-d644c854-cba4-11e7-9261-000bfe0c1158.jpg)

**Comment by gregsaun** [comment]
Cool! Do you find it sturdier? Do you see a difference in print quality?

**Comment by zagarolo** [comment]
si molta differenza no wobbling qualità superiore

**Comment by zagarolo** [comment]
ci sono un po di peli

**Comment by gregsaun** [comment]
This is due to the filament, you can remove them using a hair gun : 
https://www.youtube.com/watch?v=uqUcrIsSHak
You can also play with retraction but I never tried

**Comment by gregsaun** [comment]
You can try to reduce temp a bit as well, I am at 225°C

**Comment by zagarolo** [comment]
print 205

**Comment by zagarolo** [comment]
Hi problem wobbling
![img_20171118_143857](https://user-images.githubusercontent.com/6859327/32980966-3efbdd76-cc70-11e7-97ca-ef4f46d93d0f.jpg)

**Comment by gregsaun** [comment]
It does not look to be a wobbling issue to me.

* If the part is brittle, then you should increase temp and print slower
* Clogged nozzle?
* Does the temperature variate during the print?
* Filament is getting stock or tangled

**Comment by zagarolo** [comment]
![15112603062136314018810176024653](https://user-images.githubusercontent.com/6859327/33067835-b66bc268-ceaf-11e7-80b3-fe2475cc6a65.jpg)


https://github.com/prusa3d/Prusa-Firmware/issues/75#issuecomment-311386115

Sebastianv650/Prusa-Firmware/tree/MK2_Community_Mod

Very very good

**Comment by gregsaun** [comment]
So good, I have to update my firmware!

**Comment by zagarolo** [comment]
https://github.com/prusa3d/Prusa-Firmware/releases/tag/v3.1.0-RC2

Read

**Comment by zagarolo** [comment]
![15112671576212367766761551071050](https://user-images.githubusercontent.com/6859327/33072370-8b75c7ec-cebf-11e7-8b2d-7254a09136ea.jpg)

**Comment by gregsaun** [comment]
Yep I read it and just finished to upgrade my firmware, let's go to calibrate the K value! Very nice new feature!

**Comment by zagarolo** [comment]
Is very very faster print

**Comment by zagarolo** [comment]
Ciao mi servirebbe se possibile un grande favore non sono capace a disegnare e creare un file stl per ABS  e Mi servirebbe urgentemente una modifica sul file originale Prusa mk2s asse X end e motor adatti per cuscinetti igus 15 mm ho un grande problema ti allego la foto grazie 
![img_20171125_125055](https://user-images.githubusercontent.com/6859327/33230238-c5848fa4-d1df-11e7-83ca-c6b5c91d8c81.jpg)

**Comment by gregsaun** [comment]
Could you describe your problem?

**Comment by zagarolo** [comment]
Guarda la foto il cuscinetto si muove scende nella parte interna

Look at the photo the bearing moves down to the inside

**Comment by zagarolo** [comment]
create file in abs and petg

**Comment by zagarolo** [comment]
I would be very grateful if you could create the abs file and pet parts original X end axis, and the engine part

**Comment by gregsaun** [comment]
I do not thing it is a big deal if the bearing are going a bit inside. For now I do not have lots of time, I would like to finish the bear upgrade first to start a new one.

What you can simply do is this :
- Download MK2s scad files from here https://www.prusa3d.com/prusa-i3-printable-parts/
- Install OpenScad
- Open bearing.scad and reduce bearing_diameter value by 0.1 o 0.05mm (top of the file) and save
- Open x-end-idler.scad, then hit F6, then File -> Export -> STL
- Open x-end-motor.scad, then hit F6, then File -> Export -> STL

**Comment by zagarolo** [comment]
New project ?

**Comment by zagarolo** [comment]
Vorrei investire sto cercando di fare qualcosa di grosso cerco persone per investire denaro in nuovi progetti aprire una fabbrica io sono un costruttore di case ma ho sempre fatto elettronica vorrei investire miei soldi in qualcosa di grande

**Comment by zagarolo** [comment]
Spero che il tuo nuovo progetto usare componenti di alta qualità e tecnica superiore per pezzi

**Comment by zagarolo** [comment]
Quanti anni hai ?

**Comment by gregsaun** [comment]
Could you contact via my website here : https://www.ekunn.com/ -> contact

**Comment by zagarolo** [comment]
help I have a height problem of carriage Y extruder slams in the pot how can I change the end of the stroke find the new zero point? I modified bearings with double bearing under the carriage Y but increased height thanks

**Comment by zagarolo** [comment]
appassionato di droni ?

**Comment by zagarolo** [comment]
![img_20171202_110459](https://user-images.githubusercontent.com/6859327/33514251-d1674c64-d750-11e7-86bb-5163095ba543.jpg)
Mio drone DJI Spark modified firmware adesso può andare a 2 km o 4 km
