### ISSUE TITLE
Mk3 build from scratch so need more BOM details than upgrade

### ISSUE THREAD

**Issue by Bazmundi** [gregsaun/prusa_i3_bear_upgrade#102]
I bought a bear frame upgrade kit from Aliexpress (tallest one ;).

So, I have Z axis sorted.

Since there seems to be some tendency for truncated BOM for upgraders, can we get a full BOM for build from scratchers please?

In any event, can someone give a hint at the x and y 8mm rod lengths please?

Cheers,
A

**Comment by gregsaun** [comment]
Unfortunately, it is almost impossible to provide a full BOM as Prusa does not have a BOM and keep some secret parts closed source.

X smooth rod length: 370mm
Y smooth rod length: 330mm
Z smooth rod length: 320mm
