### ISSUE TITLE
Y idler for 9mm belts step file not available

### ISSUE THREAD

**Issue by haleypearse** [gregsaun/prusa_i3_bear_upgrade#111]
My idlers are all 18mm in diameter whereas the cavity in the tensioner is ~17mm. If I had the step or fusion file I could easily make the required modification. Thanks.

https://github.com/gregsaun/prusa_i3_bear_upgrade/tree/dev/optional_parts/y_idler_9mm_belt

**Comment by gregsaun** [comment]
You should think about using a smaller idler later, those cheap idlers have too big flanges which can drag and wear the belt. I'll add step files in a second ;)

**Comment by gregsaun** [comment]
Done :)

https://github.com/gregsaun/prusa_i3_bear_upgrade/commit/04889991a0d4c6dc647c66baf55d36db9cad4e24

**Comment by haleypearse** [comment]
Awesome! Thanks. The fusion file was helpful. I can put up my version somewhere, maybe thingiverse, in case someone else has a cheap idler. My version is also worse because you have to thread belt through the tensioner before installing it, because the belt wants to go through the new back hole. But otherwise it seems fine.

I'll consider replacing it, or maybe modifying it, thanks. 

BTW even worse, I found I only had 20T pulleys so I had to model up a 16T 10mm one and print it this morning \_(:/)_/

I![F2AA0D9F-E36E-447E-B1F5-31BCD9105CC5_1_105_c](https://user-images.githubusercontent.com/10296672/81195864-37e53280-8f73-11ea-829c-512da0348563.jpeg)

**Comment by gregsaun** [comment]
Thanks for the feedback and happy you could modify it. You can for sure add this to Thingiverse if you like, some people might be interested. However, I am not sure I want to add to list of optional parts from the community yet, I will see if I get this request regularly or not, for now you were the first one.
