### ISSUE TITLE
y_bearing_holders Orientation dots

### ISSUE THREAD

**Issue by jigsawgirl** [gregsaun/prusa_i3_bear_upgrade#118]
It appears the position of the orientation dots shown on the y_bearing_holders in the assembly guide diagram don’t match the position of the orientation dots on the printed parts.

**Comment by gregsaun** [comment]
Do you follow the new assembly guide? Here is the chapter where you assemble the Y bearing holders:
https://guides.bear-lab.com/Guide/05.+Y+axis+motion/46?lang=en

**Comment by jigsawgirl** [comment]
Sorry. I was looking at the MK2.5 diagram but had the MK3 part. I did not realise that the parts were different.
