### ISSUE TITLE
optional LCD cover does not fit the lcd supports (version 2.1)

### ISSUE THREAD

**Issue by domhardt** [gregsaun/prusa_i3_bear_upgrade#120]
The optional [LCD cover with text](https://github.com/gregsaun/prusa_i3_bear_upgrade/blob/master/optional_parts/lcd_cover/printed_parts/stl/lcd_cover_text.stl?raw=true) has not enough space in the back to fit the [lcd_support_a](https://github.com/gregsaun/prusa_i3_bear_upgrade/blob/master/optional_parts/lcd_cover/printed_parts/stl/lcd_support_a.stl?raw=true) and [lcd_support_b](https://github.com/gregsaun/prusa_i3_bear_upgrade/blob/master/optional_parts/lcd_cover/printed_parts/stl/lcd_support_b.stl?raw=true). I refer to the version 2.1

**Comment by gregsaun** [comment]
Hello, are you using the official Prusa LCD screen or an LDO Motor one?

**Comment by domhardt** [comment]
Hello, as I got my printer from someone else I had to re-check everything. All dimensions of my parts are identical to the components from the Fusion360 project of this repo. So in the next step I assembled the components in Fusion360 and there is not enough space in the LCD cover for the LCD support brackets. Please see the attached images and the [Fusio360 project](https://a360.co/2LOxcg5).

![Bildschirmfoto 2021-01-23 um 00 46 18](https://user-images.githubusercontent.com/1955290/105560754-0f75b200-5d15-11eb-969d-a30f1d3403ef.png)
![Bildschirmfoto 2021-01-23 um 00 48 18](https://user-images.githubusercontent.com/1955290/105560760-1270a280-5d15-11eb-9a27-925251cb2703.png)

**Comment by gregsaun** [comment]
Oh I see, you are not using the correct mount. The custom cover comes with different mounts that are attached with 4 M3x10 screws. Check lcd_support_a and lcd_support_b here: https://github.com/gregsaun/prusa_i3_bear_upgrade/tree/master/optional_parts/lcd_cover/printed_parts/stl . (note the lcd_support_x_prusa is for original Prusa frame)

**Comment by domhardt** [comment]
> Oh I see, you are not using the correct mount. The custom cover comes with different mounts that are attached with 4 M3x10 screws. Check lcd_support_a and lcd_support_b here: https://github.com/gregsaun/prusa_i3_bear_upgrade/tree/master/optional_parts/lcd_cover/printed_parts/stl . (note the lcd_support_x_prusa is for original Prusa frame)

Oh, sorry. This is my fault then. Thank you for clarifying that. I will close this issue then. Sorry for bothering you.

Keep on the good work!
