### ISSUE TITLE
2.0 Frame clarification and print Bed question

### ISSUE THREAD

**Issue by rbicelli** [gregsaun/prusa_i3_bear_upgrade#121]
Hi! I'm assembling a Prusa Bear starting from an old Geeetech i3. I have 2.0 frame (Y axis 311 mm long).
I need to change the print bed and Y alu carriage, but I can't find any useful information regarding supported print bed size.
Does MK52 bed (264x254mm) fits in the 2.0 frame?
And with 2.0 frame can I use printed part of 2.1 except the y tensioner?
Thanks

**Comment by gregsaun** [comment]
Hello, I have made compatible parts for the smaller 2.0 frame to make it compatible, here they are:
https://github.com/gregsaun/prusa_i3_bear_upgrade/blob/master/optional_parts/bear_2.0_upgrade_mk2-2s-2.5-2.5s/README.md

Yes the MK52 bed from MK2.5 is working perfectly.

You can't mix 2.0 and 2.1 parts for the Y axis, the belt path is slightly different.
