### ISSUE TITLE
BearMera, will there be support for the Trianglelab Matrix/Lite?

### ISSUE THREAD

**Issue by ossnorry** [gregsaun/prusa_i3_bear_upgrade#123]
Trianglelab has recently released the lite version of their Matrix extruder, giving a huge subtraction to the weight of the extruder body. Due to being 90% the same as the Hemera design, can we expect to see support for it? Considering the weight benefits. 
https://www.aliexpress.com/item/1005002841523390.html

**Comment by gregsaun** [comment]
Hello, I have no plan to support the Matrix nor the Matrix Lite sorry. My Fusion 360 CAD files and STEP files are available here if you like to modify it:
https://github.com/gregsaun/bear_extruder_and_x_axis/tree/master/optional_parts/bear_hemera/source
