### ISSUE TITLE
LCD frame

### ISSUE THREAD

**Issue by trionyx02** [gregsaun/prusa_i3_bear_upgrade#125]
Hi, could you please share the LCD screen cover and holder (left and right) CAD drawing in .ipt format as well? (Inventor  2018)
I have a Fysetc kit, which display won't fit into the cover and the holder s also do not fit perfectly. I would like to modify the model for me. thanks

**Comment by gregsaun** [comment]
I am sorry but I don't have IPT files exported, you can open the Fusion 360 files with a free Fusion 360 license and export IPT. F3Z file from Fusion 360 is available here: https://github.com/gregsaun/prusa_i3_bear_upgrade/tree/master/optional_parts/lcd_cover/cad_files as well as STEP files.
