### ISSUE TITLE
Xyz calibration

### ISSUE THREAD

**Issue by gleny91** [gregsaun/prusa_i3_bear_upgrade#134]
When beginning to go probe 4 points saying check all axes.

**Comment by gregsaun** [comment]
Hello, what extruder are you using?

**Comment by gleny91** [comment]
I bought the one like the prusa

**Comment by gleny91** [comment]
It came with the kit

**Comment by gregsaun** [comment]
Is it an official Prusa kit?

**Comment by gleny91** [comment]
No i bought it from aliexpress

**Comment by gleny91** [comment]
Bought whole kit not upgrade

**Comment by gregsaun** [comment]
Ok so we don't really know what it is. Could you share a picture of the X axis and extruder?

**Comment by gleny91** [comment]
I am attaching ohotos

**Comment by gleny91** [comment]
I don't know why they are not uploadingg

**Comment by gleny91** [comment]
> ``

**Comment by gregsaun** [comment]
you can drag and drop then in the issue directly. Otherwise you can use a site like Imgur

**Comment by gleny91** [comment]
I am attaching photos but nothing is happening

**Comment by gleny91** [comment]
Can we talk somewhere else ?

**Comment by gleny91** [comment]
Could it be because it has original prusa firmware ?

**Comment by gregsaun** [comment]
Yes if you have the Bear extruder this is why I wanted to see which one you have

**Comment by gregsaun** [comment]
> Can we talk somewhere else ?

[here](https://guides.bear-lab.com/Wiki/Bear_FAQ?revisionid=HEAD#Section_How_could_I_contact_you)

**Comment by gleny91** [comment]
Yes wherre ? Facebook ?

**Comment by gleny91** [comment]
I fon't know why pics not uploading

**Comment by gregsaun** [comment]
> I fon't know why pics not uploading

Use imgur

> Yes wherre ? Facebook ?

Discord, Twitter, Mastodon, Facebook and here

**Comment by gleny91** [comment]
I sent a request on facebook

**Comment by gregsaun** [comment]
I have answered on Facebook.
