### ISSUE TITLE
Tune/change filament from LCD-menu causes misalignment

### ISSUE THREAD

**Issue by FrHePo** [gregsaun/prusa_i3_bear_upgrade#142]
**Printer data:**
Printer type: MK3S
Printer firmware version: 3.13.2
Print via SD card
Bear parts: Lecktor Technologies OÜ - Värvi 5 C400-1 - 10621 Tallinn - Estonia
The Y-axis extrusion length is 331mm
All parts are original Bear.
The distance between the Y-rodholders is 311mm. The distance between the left side bearings is 93.8mm. This results in a max. build-plate travel of 217.2mm. The position of the Z-profiles was determined with the printed build_helper_z.stl-part (106 +/- 0.5mm). Mine measured 105.6mm.
See also: https://github.com/prusa3d/Prusa-Firmware/issues/4498

**Problem description:**
When changing filament during printing with the LCD-function <Tune/change filament> the print head doesn't return to the correct position creating a Y-misalignment of about +0.7mm.
After I noticed this I did a cube test print (see picture) which confirmed me that this misalignment is independent of the printed object or the G-code. It's obvious that when the build-plate travels to the change filament position it runs into the Y-limit (by 0.7mm) which is actually an unintended collision.

![P1060828](https://github.com/gregsaun/prusa_i3_bear_upgrade/assets/50290993/cbe8fa6b-8c5c-4272-bfda-05829f981c63)

![P1060830](https://github.com/gregsaun/prusa_i3_bear_upgrade/assets/50290993/131d5c97-2e82-42e3-8951-762626b46f54)
![P1060839](https://github.com/gregsaun/prusa_i3_bear_upgrade/assets/50290993/933caa0a-849d-4972-acdd-0cf878580edc)

![P1060843](https://github.com/gregsaun/prusa_i3_bear_upgrade/assets/50290993/9f67a7e2-f78e-4b6f-bc02-60a9fa5eb68f)
![P1060842](https://github.com/gregsaun/prusa_i3_bear_upgrade/assets/50290993/ab51049e-bc31-40ff-aa28-82e779f365bf)
![P1060841](https://github.com/gregsaun/prusa_i3_bear_upgrade/assets/50290993/4858d95e-84bf-4d29-b903-949e8593cccc)

**Comment by FrHePo** [comment]
@gregsaun My (outside/max.) distance between the left side Y-bearings is 93.8mm. Could you check this please?
![grafik](https://github.com/gregsaun/prusa_i3_bear_upgrade/assets/50290993/224bade6-ea07-42ba-978b-1f491dea6590)

**Comment by gregsaun** [comment]
Sorry I can't check CAD for now but you can open the source file to check (Fusion 360).

I am wondering if the distance of the nozzle or the Pinda is closer to the X axis than what it should be. Where is this extruder coning from?

**Comment by FrHePo** [comment]
AFAIK the extruder is not involved in this problem. It's the build-plate that can't travel far enough (by only 0.7mm!) to reach the hard coded (firmware) filament change position. When calling the filament change by LCD-menu the build-plate is moved to the filament change position. My build-plate can't reach this position by 0.7mm. The left-side Y-bearing bangs into the Y-rodholder and can't travel any further.
My extruder is a combination of the Orbiter 2.0 and the E3D Revo Micro.
![grafik](https://github.com/gregsaun/prusa_i3_bear_upgrade/assets/50290993/ea9e528c-bf1d-4112-9215-93f241b7da7f)

**Comment by FrHePo** [comment]
3d-gussner stated: _We have defined [FILAMENTCHANGE_[XPOS|YPOS|ZADD] = X211 Y0 Z+2](https://github.com/prusa3d/Prusa-Firmware/blob/v3.13.2/Firmware/variants/MK3S.h#L359-L361) which are fine for our printers. And normally the Y axis can travel from [Y-4 up to 212.5] so for the stock printers it has some tolerances._
Standard MK3S Y-travel is [Y-4 up to 212.5]: 216.5mm
My max. Bear Y-travel is 217.2mm. So the max. Y-travel is not the problem. This leaves only 2 options for me: 1. The Y-bearings position is incorrect or 2. The position of the Z-profiles (frame) is incorrect and must be moved 5mm backwards.
The 1st option seems impossible to me. The Y-bearing-position cannot be incorrect by 5mm. That leaves only option 2 which means that the position of the Z-profiles (frame) is incorrect.
To be sure I'll check the Pinda-position anyway.

**Comment by FrHePo** [comment]
Standard MK3:
![grafik](https://github.com/gregsaun/prusa_i3_bear_upgrade/assets/50290993/990aff6f-6183-4535-adb5-f8c7afcc1ff5)

My Extruder:
![grafik](https://github.com/gregsaun/prusa_i3_bear_upgrade/assets/50290993/eee73c1f-aca2-4145-986a-c49f7ffd249f)

So my pinda position is 3.5mm (in Y-direction) closer to the X-axis than the standard MK3. Hmm.... Could that be causing the misalignment?

**Comment by gregsaun** [comment]
You can check the dimensions of the frame here:
https://github.com/gregsaun/prusa_i3_bear_upgrade/blob/master/mechanical_drawings/bear21_frame_size.pdf

But Yes I suspect it is your extruder. Probably during calibration they stock somewhere the 0.0 point and would be different for you.

**Comment by FrHePo** [comment]
Ok. I'll correct the Pinda position and hope and see :-))

**Comment by FrHePo** [comment]
@gregsaun / @3d-gussner
After correcting the Y-Pinda-position by 3.5mm the misalignment has been cured. Thanks for your support! It made me a little wiser :-))
![grafik](https://github.com/gregsaun/prusa_i3_bear_upgrade/assets/50290993/c60e669e-8b44-4a94-94ec-ce43e26b2478)

**Comment by gregsaun** [comment]
Good news. I close it then.
