### ISSUE TITLE
MK3 Full: Y-Motor mount different between STL and assembly instructions

### ISSUE THREAD

**Issue by DoItWithASmile** [gregsaun/prusa_i3_bear_upgrade#15]
I noticed an issues in the MK3 assembly instructions with regards to the y-motor mount:
Step 3.2: 2x tee nuts are inserted in the same slot. Later on the y-motor will be installed here, see step 8.2
![image](https://user-images.githubusercontent.com/36856607/36805979-fca8d3a8-1cbe-11e8-88a7-15a8f11f67bb.png)

However, the y-motor mount in the STL uses two nuts in two slots on the same side:
![image](https://user-images.githubusercontent.com/36856607/36805211-1daf75ea-1cbd-11e8-8250-b24bea6ceffb.png)

Option 1: instructions are outdated
- add 3rd tee nut
- modify fig 8.2 to depict current mount

Option 2: mount is outdated
- update STL

**Comment by gregsaun** [comment]
That was the STL like in issue #16. I close this one as it as been fixed now. Thanks for reporting this.
