### ISSUE TITLE
MK3 Full: Y-Mount different from MK2(.5s)

### ISSUE THREAD

**Issue by DoItWithASmile** [gregsaun/prusa_i3_bear_upgrade#16]
The y-motor mount of the MK3 is different to the MK2s in one important way:
the MK2s mount uses 3 screws to fix the motor, the MK3 mount only uses 2. Is this intentional?

MK2s:
![image](https://user-images.githubusercontent.com/36856607/36806303-ec7238c0-1cbf-11e8-890d-77763f494c45.png)

MK3:
![image](https://user-images.githubusercontent.com/36856607/36806263-c573709a-1cbf-11e8-8774-1ed80152d279.png)

Since both mounts are for NEMA 17, the holes should be same.

BTW: The after market EINSY board can be bought with an endstop! so even though Prusa Research does not ship the MK3 with one, it would not be a problem to reuse the MK2s mount design with endstop.

**Comment by gregsaun** [comment]
This is a bug, it is like my MK3 part is an older one, it should have 3 screws. BTW, original MK3 has only two

**Comment by gregsaun** [comment]
I have exported the last version, that was an export issue. I keep this issue open until I have double check all exports. Thanks for reporting this :wink:

**Comment by DoItWithASmile** [comment]
I know the original MK3 version only has 2. However, in the forum there were different beefed up designs:
- 3 screws to the backplate (included drilling holes... with the V-slot we can do this way easier)
- 3 screws to the stepper motor
- and even one where the stepper motor was held from both sides (that is what I printed: the y-mount from the STLs and a mirrored version for the other side of the motor. Quick and dirty. 😈)

**Comment by gregsaun** [comment]
Yes you are right, I really do not understand the design of the original mount. Only two screws to mount the motor plus the arm are thinner than MK2s design...

I do not know the third design, do you have a link?

BTW, really sorry for this mistake, you will need to print one more, I hope you have enough filament...

**Comment by DoItWithASmile** [comment]
I can confirm the newly exported STL looks like the assembly instructions.
Will print those with the next batch. New spool of filament arrived today. I am safe. 😃

Link to design no. 3: Prusa forum, ["Fine tune your MK3 Y axis"](https://shop.prusa3d.com/forum/original-prusa-i3-mk3-f30/fine-tune-your-mk3-y-axis-t13851-s20.html#p63825), rendering from RHD
![image](https://user-images.githubusercontent.com/36856607/36813074-90d7d51a-1cd3-11e8-9620-4bbbe4d0f82e.png)

**Comment by DoItWithASmile** [comment]
I guess so. Couldn't find specs on the screws though. I guess I have to unscrew one to measure it...
Might check tomorrow since the printer is running.

**Comment by Panayiotis-git** [comment]
If you intent to remove the screws from the back of the motor, be careful not to remove the rotor from the motor. It could result in a dramatic loss of motor torque at some steppers.

**Comment by DoItWithASmile** [comment]
Good point. I just removed one. It's a M3 x 30 mm.
