### ISSUE TITLE
End caps on z-axis missing?

### ISSUE THREAD

**Issue by DoItWithASmile** [gregsaun/prusa_i3_bear_upgrade#17]
The extrusion of the z-axis is not covered by end caps.
![image](https://user-images.githubusercontent.com/36856607/36806965-fcb94e06-1cc1-11e8-843c-df25c0832d89.png)

Suggestion: add a pair of end caps
- BOM: Add 1x pair of end caps, add 4x set screws
- add instructions to step 12 (at least for MK3)

**Comment by gregsaun** [comment]
Yes I did not design them, they have to be a bit different than the one with the bear. I was hesitating between: 

- 3d printed one with set screws mount
- 3d printed one with self tapping screws on top
- Openbuilds end caps http://openbuildspartstore.com/end-cap/

What do you think?

**Comment by DoItWithASmile** [comment]
To stay true to the Bear Upgrade, here is my current thinking:

1. use 3D printed ones with set screws
2. why not ever so slightly modify the end caps we have:
![image](https://user-images.githubusercontent.com/36856607/36811301-8e5f168c-1ccd-11e8-8b09-d5c175013488.png)

This should fit here
![image](https://user-images.githubusercontent.com/36856607/36811327-ac07659a-1ccd-11e8-9702-21d5c75591b8.png)

**Comment by gregsaun** [comment]
The problem are vibrations, this is why I have decided to use set screws and not only something that "clip" inside. Those "feet" for set screws are quite fragile and it is not really possible to make them stronger. So I like to keep the third "foot" in case one break or if you would to add one more screw.

I think I will purchase some self tapping screws for testing a first

**Comment by DoItWithASmile** [comment]
In your experience did one ever break off due to vibrations?

Even a Bear Upgrade will be suspect to vibrations. That's for sure.
However, end caps are not load bearing. And wonder how and why they would break. 🤔

**Comment by gregsaun** [comment]
I was not clear sorry, this is not a problem of breaking due to vibration, but the noise they can make if there are vibrating (because not correctly maintained).

Yes for sure Bear Upgrade will vibrate. Or it means you are not printing faster enough :grin:
