### ISSUE TITLE
MK3 Full: Step 4.1 not possible

### ISSUE THREAD

**Issue by DoItWithASmile** [gregsaun/prusa_i3_bear_upgrade#18]
In step 4.1 it is instructed to put 4x black corners on.
However, the tee nuts on the 331 cm extrusions cannot be added without taking everything apart again.

Option 1:
The tee nuts have to be added before step 2.5

Option 2:
Add drop-in tee nuts to the BOM. Those can be added after the fact.

**Comment by gregsaun** [comment]
Thanks!
