### ISSUE TITLE
Interference with psu_lower_mount and latest PSU cover

### ISSUE THREAD

**Issue by gregsaun** [gregsaun/prusa_i3_bear_upgrade#2]
From Jeepguy42 on Thingiverse :
https://www.thingiverse.com/thing:2562174/#comment-1551150
http://www.openbuilds.com/threads/prusa-i3-bear-edition.10274/#post-58904

**Comment by zagarolo** [comment]
hi thank you for your reply...

you add print setting is for all parts or only psu and holder mount ? thanks

**Comment by zagarolo** [comment]
drill new holes print 3d for frame Z ?

**Comment by gregsaun** [comment]
Zagarolo> I have created a new issue for your question, I would like to keep this issue clean and focused to the psu_lower_mount / psu cover only. Here is the new issue : #3
