### ISSUE TITLE
Calibration point can't be reach

### ISSUE THREAD

**Issue by gregsaun** [gregsaun/prusa_i3_bear_upgrade#20]
Issue from adam6666 :

> Hello Greg
> There is a slight issue which I am facing. My printer is complete but during calibration, it shows left front calibration point can't be reached. Although when I check it manually, the pinda probe is exactly in the center of it. Please advise

**Comment by gregsaun** [comment]
Which version did you build Full or Half Upgrade?

Which calibration point can't be reach?

**Comment by adam6666** [comment]
Full upgrade Mk2s, it shows "LEFT FRONT CALIBRATION POINT" can't be reachead

**Comment by gregsaun** [comment]
So this seems to be the first point, did it scratch your bed?

If you confirm it is the first point, then try to lower a bit the PINDA probe.

**Comment by adam6666** [comment]
Yes, it is the first point, but it didn't scratch the surface. I will lower probe a bit more and see what is the result.

**Comment by gregsaun** [comment]
Hi adam6666, did you solve your issue? Can I close?

**Comment by gregsaun** [comment]
I am closing it because no more activity
