### ISSUE TITLE
BOM quantities and link to Tee-nuts and screws needs update. Store offers only 10pce pack, not 25pce pack.

### ISSUE THREAD

**Issue by ddpalmer** [gregsaun/prusa_i3_bear_upgrade#21]
The BOM https://github.com/gregsaun/prusa_i3_bear_upgrade/blob/master/full_upgrade/for_mk2.5/manual/bom.md
lists quantities and links for Tee-nuts and Low Profile M5 screws for (25pce pack) but it appears that the store now offers only (10pce pack).

For example, for the Tee-nuts: the link in the BOM is http://openbuildspartstore.com/tee-nuts-25-pack/ 
but this is redirected by the store to http://openbuildspartstore.com/tee-nuts-10-pack/
The quantity in the BOM is listed as 4, but should be 9.

Similar change needed for the screws.

I can make the changes and submit a PR if you like.

**Comment by gregsaun** [comment]
Ok that is new thank you! I will go to exact number and do not mention pack size anymore (some shops are also selling time by 1)
