### ISSUE TITLE
End_Cap_Z_Axis Not in Print Settings Page (for MK2.5 at least)

### ISSUE THREAD

**Issue by jhoff80** [gregsaun/prusa_i3_bear_upgrade#25]
Minor thing as I assume you used the same settings as the other end caps, but still.

Also, if I could make a suggestion, having a separate table for quantity of printed parts on one page, and then a table for print settings on another page doesn't make much sense to me.  Maybe just put a column for quantity in the print settings table and link from the BOM to it?

**Comment by gregsaun** [comment]
thanks for reporting, I'll fix this and then switch this issue as improvement for the table.
