### ISSUE TITLE
MK2.5 Full Step 18 - Needs reference to MK2.5 additional Y-connectors

### ISSUE THREAD

**Issue by jhoff80** [gregsaun/prusa_i3_bear_upgrade#26]
https://github.com/gregsaun/prusa_i3_bear_upgrade/blob/master/full_upgrade/for_mk2.5/manual/assembly_instructions/step18.md

Currently it says to follow the MK2S instructions for assembly, but there are some extra cables to connect as described in manual.prusa3d.com/Guide/6.+Electronics/573?lang=en

**Comment by gregsaun** [comment]
Thanks for reporting this :)
