### ISSUE TITLE
[Full MK2 MK2.5] Add support on back of Y motor

### ISSUE THREAD

**Issue by gregsaun** [gregsaun/prusa_i3_bear_upgrade#34]
Could be nice to have support on the Y motor, just like on the original design there's a part that goes behind the motor to make it lay flat to the rods

This will make sure motor will be 100% perpendicular and mount will not bend with higher temperature of the motor

**Comment by gregsaun** [comment]
Needed only for full and half MK2(s) and MK2.5

**Comment by Panayiotis-git** [comment]
Just a note: This small piece of ABS plastic, at my MK2s/MK2.5 contributes a lot to the Y-axis noise. I have replaced it with a rubber foot of the same size and the fast moves of the bed are much less noisy.

**Comment by gregsaun** [comment]
Will be done differently ;-)
