### ISSUE TITLE
Sources for extrusion

### ISSUE THREAD

**Issue by FischOderAal** [gregsaun/prusa_i3_bear_upgrade#4]
I've seen that you plan to cut everything yourself. Sometimes this and openbuilds (due to taxes) is not an option, so maybe it makes sense to list options where you can order the pieces pre-cut. For Germany good sources are:
http://www.motedis.com
http://kritec-gmbh.de

**Comment by gregsaun** [comment]
Good idea, we can start listing few here. Please, anyone know a good one, please help us to complete the list :)

UK : ooznest.co.uk (very good)
Portugal : http://www.ratrig.com (not tested)

**Comment by FischOderAal** [comment]
Some more:
Germany: http://www.watterott.com/de/Mechanik/V-Slot-Profile
Germany: http://www.conucon.de/de/29-openbuilds
France: http://www.vslot-europe.com/home/8-vslot-rail.html
Switzerland: https://www.3dware.ch/OpenBuilds-V-Slot-Profil-20mm-x-40mm-x-1000mm-De.htm

I also found this:
https://www.google.com/maps/d/u/0/viewer?mid=1pluH7gcGIW6e3wA9oDI7jkD65Ds&hl=en_US&ll=49.25723077144779%2C9.548680559375043&z=6

That was all I could find while going through a mug of coffee :)

**Comment by gregsaun** [comment]
Forget to say thank you FischOderAal, sorry! Thank you then :)

I have added a page with online shops selling official Openbuilds hardware (and pre-cut option) : https://github.com/gregsaun/prusa_i3_bear_upgrade/blob/master/doc/openbuilds_shop_list.md

**Comment by DoItWithASmile** [comment]
This is more FYI:
I received my hardware from RatRig today. Here is something I really don't like with most shops listed:

The tee nuts are terrible!
![image](https://user-images.githubusercontent.com/36856607/36813767-e84c2db2-1cd5-11e8-8caf-129092c601d5.png)

This is how a proper tee nut should look like IMHO:
![image](https://user-images.githubusercontent.com/36856607/36813807-02ecf30e-1cd6-11e8-9fd5-2e38ba45f67e.png)

**Comment by gregsaun** [comment]
They look like similar to Openbuilds tee nuts : 
![makerlink_single_tee_nut_2_clear__97926 1498230389 1280 1280__24539 1509730862](https://user-images.githubusercontent.com/12335098/36814917-539ed4c2-1cd9-11e8-8d79-81725fd8868e.png)

I totally agree they are not the best one but they work pretty well and they are cheaper than "bigger" ones.

**Comment by DoItWithASmile** [comment]
Found a shop in Algeria offering v-slot heavy duty nuts for 0.10 EUR per piece 😅 
www.dzduino.store

No pre-cutting of extrusions though.

**Comment by gregsaun** [comment]
I did not realize yesterday but those type of tee nuts will enter in contact with my printed parts due to the extra material on top

![](https://user-images.githubusercontent.com/36856607/36813807-02ecf30e-1cd6-11e8-9fd5-2e38ba45f67e.png)

However this type will be good (from dzduino.store) : 
![](https://www.dzduino.store/image/cache/catalog/product/1700/62/DZD001762-800x800.jpg)

**Comment by dukemagus** [comment]
https://www.tdtec.com.br/

These guys sell 20x40 aluminum profiles on the openbuilds.com format in Brazil.

You'll need to contact them to be sure of which other related components they sell, though

**Comment by gregsaun** [comment]
Thank you, I have added them to the list. tdtec.com.br does not work in my country, are you sure about the link?

**Comment by Panayiotis-git** [comment]
Greece: https://grobotronics.com/mechanics-and-wheels/openbuilds-v-slot/

**Comment by gregsaun** [comment]
Thanks!

**Comment by adam6666** [comment]
India - https://www.3dprintronics.com/Aluminium-Extrusions-c7124102 . They have V Slot extrusions and accessories but are not official V Slot distributors.

**Comment by fishmsk** [comment]
Russia - https://soberizavod.ru/
They have aluminum extrusions, screws, tee nuts, plates etc. The only difference from Openbuilds' extrusions is a hole - it is for M6 thread here (Openbuilds ones have holes for M5 thread).

**Comment by gregsaun** [comment]
Thank you all, we start to have a nice list :)

fishmsk > Do you mean the tee nuts are M6? Do they propose cutting service?

**Comment by adam6666** [comment]
https://www.3dprintronics.com/Aluminium-Extrusions-c7124102 these guys provide precise customized lengths of all the T slots and V Slots.

**Comment by fishmsk** [comment]
gregsaun -> Yes, they provide cutting service.
I mean not Tee nuts hole but the hole in the extrusion itself. Please see the drawings below:
[http://protein.nmr.ru/fish/pics/soberizavod_vs_openbuilds.jpg](url)

**Comment by gregsaun** [comment]
Thanks  adam6666 and fishmsk.

I have just added new stores in Canada, Norway, Spain and Sweden.

**Comment by DoItWithASmile** [comment]
Denmark: https://3dnielsen.dk

Didn't check if they offer pre-cut.

**Comment by DoItWithASmile** [comment]
They to offer pre cut with +/- 0.5 mm

**Comment by gregsaun** [comment]
Thank you, it's in  :)

**Comment by adam6666** [comment]
Hello Greg
There is a slight issue which I am facing. My printer is complete but during calibration, it shows left front calibration point can't be reached. Although when I check it manually, the pinda probe is exactly in the center of it. Please advise

**Comment by gregsaun** [comment]
Hi adam, I have opened a new issue here : https://github.com/gregsaun/prusa_i3_bear_upgrade/issues/20

**Comment by jhoff80** [comment]
Will the RatRig kits still need the joining plates to be filed down slightly?  I assume so, but just wanted to check before buying a tool for that.

**Comment by gregsaun** [comment]
That is a good question because they are coming in black! No one report something about this and I do not have RatRig plates in hand so hard to give an precise answer. I will ask RatRig directly and come back to you ;)

**Comment by gregsaun** [comment]
Got an answer from RatRig, plates are not sharp like original Openbuilds plates so no need to file them. I'll add a note in the manual. Thanks for reporting :-)

**Comment by kberck** [comment]
Does the extruded aluminum have to be v-slot specifically?  I have some t-slot available, but it doesn't have the chamfered edge of the v-slot.  Wanted to check before I start cutting so I don't hit a roadblock later on.
Thanks!

**Comment by gregsaun** [comment]
@kberck yep this is mandatory because of the way my parts are designed. Also check here : 
https://github.com/gregsaun/prusa_i3_bear_upgrade/issues/39

**Comment by martinkaersgaard98** [comment]
To the list of sources of V-slot rail and other OpenBuilds parts you can add Danish shop: makersupplies.dk

**Comment by sparkyman215** [comment]
The NA - Texas distributor: smw3d tries to redirect to hobby-fab.com, a parked website. Suggest removing from list

**Comment by gregsaun** [comment]
@sparkyman215 thanks!
