### ISSUE TITLE
MK3 Full Upgrade Step 6 Missing info?

### ISSUE THREAD

**Issue by ftKnox** [gregsaun/prusa_i3_bear_upgrade#40]
Is it just me or does step 6 in the full upgrade manual not show the required 4 tee nuts for the hinge and power supply mounts?

**Comment by gregsaun** [comment]
You can insert them from top later :-)

**Comment by ftKnox** [comment]
wow that's embarrassing... now to quickly close this before anybody see's it :)

**Comment by gregsaun** [comment]
hahaha you are not the first to ask for this! There is no stupid questions :-)

**Comment by yellobello** [comment]
@ftKnox 👍 Wow, it´s closed for over a year now but still not in the manual ... just had to open the frame again to insert t(h)e nuts.

**Comment by gregsaun** [comment]
@yellobello sorry for the inconvenience and time it takes. I was really busy with the extruder. Will be back on the frame soon.

In the mean time you can create pull request, that would be very helpful. If you do so please do it for the 3 versions: MK2s, MK2.5 and MK3.

**Comment by yellobello** [comment]
@gregsaun To be perfectly embarrased, I too had to realize that most of the nuts can just be dropped in from above. But I will do so this weekend, so you just can OK the request. I am very happy that you are working on the extruder, by the way! so please continue ;-)

**Comment by gregsaun** [comment]
Thanks a lot!
