### ISSUE TITLE
spool holder for optional list

### ISSUE THREAD

**Issue by BenRoe** [gregsaun/prusa_i3_bear_upgrade#42]
This spool holder works great with the bear upgrade. https://www.thingiverse.com/thing:1832235

![Spool holder](https://dzwonsemrish7.cloudfront.net/items/1R47233n0t1J0H1F190A/IMG_5471.JPG?v=b8eddd23)

**Comment by gregsaun** [comment]
Haha this is not designed for v-slot but it works! Second time I heard that stock spool holder is working with the Bear frame. Very nice design from Martin!

However, I prefer to keep the optional part list with accessories designed for v-slot to ensure a perfect compatibility.
