### ISSUE TITLE
Small improvement of manual

### ISSUE THREAD

**Issue by daktylus** [gregsaun/prusa_i3_bear_upgrade#47]
I always search for the link of the optional printed parts (/optional_parts.md) under: "half_upgrade/manual/bom.md" or "half_upgrade/manual/print_settings.md"  . However it is first listed quite far back in step 4. "Preflight Check" . It appears intuitive and reasonable to me, to give the link also together with the standard printed parts in the manual steps mentioned above.

Update: I also noticed that in the half upgrade's BOM and list of printed parts, the quantitiy of the end caps is given with 2. However there are 4 corners and in the assembly instructions step 13 there are 4 end caps required. Maybe the intention was to print two times the stl containing 2 caps. However it is somewhat unclear. Maybe a stl with all 4 caps in it is better.

Cheers

**Comment by gregsaun** [comment]
I have some idea on how to improve optional parts location, this will be done.

Number of parts to print has been fixed with commit https://github.com/gregsaun/prusa_i3_bear_upgrade/commit/a7beaad7494e81ffe81fba6c76432ef18d1cfa63 .  Thanks for reporting it!
