### ISSUE TITLE
Having troubles with frame_drilling_dimensions.pdf 

### ISSUE THREAD

**Issue by alomex21** [gregsaun/prusa_i3_bear_upgrade#5]
I printed with adobe acrobat reader with real size, which print the size of the paper (letter in my case) intead of the whole sketch, as the result of some of the distances doubled(center of the aluminum extrusion with the edge of the z frame, which measures 120mm instead of 60mm and 40 mm instead of 20mm). Any help on this?
Thanks
![img_3180](https://user-images.githubusercontent.com/33077076/31976503-4981d270-b90e-11e7-9cbe-7ca434ff6dea.JPG)

**Comment by FischOderAal** [comment]
In the end, it is only a sketch. I guess it was scaled to emphasis the details. You should print the drill template.

**Comment by gregsaun** [comment]
I think you are both right :)

I made this drawing on A3 paper, this could explain why it is 2 times bigger. Be careful when using the printed design, carefully check all dimensions.

**Comment by gregsaun** [comment]
For your information, the problem is that I used a scale of 2:1 to make this drawing. I have fix it by adding the scale on the drawing. You should then print 2x smaller.

Thanks for your feedback  :)
