### ISSUE TITLE
Step 15 of manual for 2.5 full upgrade.  M3 nut is called a bolt.

### ISSUE THREAD

**Issue by Tarpon907** [gregsaun/prusa_i3_bear_upgrade#58]
In the parts list:
1x M3 bolt (from the original PSU lower mount)

and in in assembly steps:
Add M3 bolt into the psu_lower_mount (figure 15.3)

Figure 15.3 correctly calls it a nut.

**Comment by gregsaun** [comment]
Thanks :-)
