### ISSUE TITLE
Assembly instructions Step 7 for MK3 Full Upgrade incorrectly refers to a length as 96mm

### ISSUE THREAD

**Issue by matthew-humphrey** [gregsaun/prusa_i3_bear_upgrade#60]
For the MK3, the "assembly helper" is 106mm, not 96mm. In the assembly instructions, Step 7 correctly refers to the distance as 106mm in item 3, but in item 4 incorrectly refers to this distance as 96mm. It appears this is a copy and paste error from the MK2/S or MK2.5 assembly instructions.

**Comment by gregsaun** [comment]
Thanks!
