### ISSUE TITLE
Some vendors have pre-tapped 359mm v-slots

### ISSUE THREAD

**Issue by matthew-humphrey** [gregsaun/prusa_i3_bear_upgrade#66]
The All3dMakers full Bear kit has pre-tapped 359mm v-slots, so Assembly Instructions Step 5 is not needed. Kits from other vendors sourcing the extrusions from LDO probably don't need this either. It's worth mentioning in the instructions, because only one end of the extrusion is tapped, and it's very possible not to notice it.

**Comment by skieast** [comment]
The extrusions I just received from Ratrig were tapped as well.

**Comment by gregsaun** [comment]
Yes this will change soon, everyone will get tapped extrusion ;-)
