### ISSUE TITLE
Hey Greg there's Prusa contest at myminifactory you could enter!

### ISSUE THREAD

**Issue by Pathogenius** [gregsaun/prusa_i3_bear_upgrade#68]
I just thought you might have a good chance at winning some Prusa gear at this place, GOGOGO!

https://www.myminifactory.com/competition/pimp-my-original-prusa-160

Good Luck!

**Comment by gregsaun** [comment]
Thanks a lot for thinking about me, I was not sure about it and let places for others. Anyway it is over from a long time now :-D
