### ISSUE TITLE
Ambiguous extrusion lengths

### ISSUE THREAD

**Issue by ax00b3** [gregsaun/prusa_i3_bear_upgrade#70]
The BOM says:

> 1x 311mm + 311mm + 290mm,
2x 356mm + 370mm

Is this two of everything and just one 290mm? If so, it should read

> 1x 290mm,
2x 356mm + 370mm + 311mm

Sorry to be a nag, this is the priciest part and I don't want to get it wrong because I overthink stuff.

**Comment by thespand** [comment]
Hi ax00b3,
Yes, you are correct :)

**Comment by Panayiotis-git** [comment]
I think Greg is trying to optimize the lengths to cut from 1 meter extrusions so you will waste less material.

**Comment by gregsaun** [comment]
As this went back few times I know fixed it
