### ISSUE TITLE
Step 15, MK3, Full Bear - PSU lower mount screw length is too short

### ISSUE THREAD

**Issue by matthew-humphrey** [gregsaun/prusa_i3_bear_upgrade#71]
In the assembly instructions for the MK3 full bear, step 15, it says to use the original screw for the PSU lower mount. This is an M3x10, which is too short. The closest size in the spares bag is an M3x18, which will work.

In addition, the instruction says that the nut and washer are also from the original mount, but neither are present in the original.

I will file a PR to fix this.

**Comment by gregsaun** [comment]
Thanks!
