### ISSUE TITLE
M5x8mm Instead of M5x10mm for MK3 90 Degree Plates

### ISSUE THREAD

**Issue by jsaintro** [gregsaun/prusa_i3_bear_upgrade#74]
Building the MK3 frame with 4mm plates (3.5mm to be exact) and noticed the M5x10mm screws are about 2mm too long.  

![img_0513](https://user-images.githubusercontent.com/214990/52756710-4e9b1480-2fd0-11e9-8459-527071e3896e.jpg)

**Comment by jsaintro** [comment]
Submitted pull request #75 

Thanks for all the hard work!!

**Comment by gregsaun** [comment]
Plates should be 4mm not 3.5mm, sorry :-(

**Comment by jsaintro** [comment]
Even with 4mm plates I think it would be a close call.  Do 4mm plates also work with 8mm screws?  If so it might be nice to be compatible with both.
