### ISSUE TITLE
MK3 manual/parts: no washers

### ISSUE THREAD

**Issue by wavexx** [gregsaun/prusa_i3_bear_upgrade#78]
I purchased the MK3 in november last year (extruder R3 parts for a reference). There are no washers in the original build. I assume there were some earlier.

8 M3 washers are added to the z_motor_mounts and one for the psu_lower_mount.

The kit from Ratrig I got included 12mm black button-head M3 screws, but no washers.

**Comment by gregsaun** [comment]
Thanks for that! Did not know they removed the washers.
