### ISSUE TITLE
On the front y-rod mounts you cannot use zip ties as the ”head” hits the bed

### ISSUE THREAD

**Issue by gregsaun** [gregsaun/prusa_i3_bear_upgrade#8]
On the front y-rod mounts you cannot use zip ties as the ”head” hits the bed

Found in the comments here :
https://www.facebook.com/photo.php?fbid=1737186839633533&set=gm.828999217284561&type=3&theater&ifg=1

**Comment by zagarolo** [comment]
Hi 
On the front y-rod mounts you cannot use zip ties as the ”head” hits the bed

YES
