### ISSUE TITLE
It's Bear Upgrade ready for MK3S?

### ISSUE THREAD

**Issue by OrwillT** [gregsaun/prusa_i3_bear_upgrade#82]
Hi,
I just want to build a fresh new Prusa i3 MK3S by my own, and I want to use bear upgrade.
I fond that in issue #67 you said you are working on MK3S and should be out that week. So is it ready to be use now?
Thanks for your incredible job.

**Comment by Sugar250** [comment]
And also #79

**Comment by rafaljot** [comment]
I upgraded my mk3s using
- https://www.thingiverse.com/thing:3469271
- https://github.com/gregsaun/bear_extruder_and_x_axis/tree/dev/printed_parts/stl/mk3_mk3s
- https://github.com/gregsaun/bear_extruder_and_x_axis/tree/dev/printed_parts/stl/common_to_all_versions

**Comment by gregsaun** [comment]
Yes but you have to use the belt holder from MK3. Y axis will get a rework to add tensioner on all versions

**Comment by codingcatgirl** [comment]
To anyone who might be reading this (outdated) issue looking for an answer, let me save you some time: The dev branch is compatible with the MK3S, and any 2.1 release is as well, you can just check out that tag.
