### ISSUE TITLE
New Delta PSU

### ISSUE THREAD

**Issue by Wiggleplum** [gregsaun/prusa_i3_bear_upgrade#83]
It appears Prusa is shipping a new PSU made by Delta with their kits, and is sending them out as warranty replacements. It seems that the lower PSU mount can not be used with it. Are there any brackets available for the full bear? I received mine today, and am wondering the best way to support it besides the two screws on the side. 
The new PSU can be seen here:
https://manual.prusa3d.com/Guide/7.+Heatbed++&+PSU+assembly+(Black+PSU)/1153

**Comment by matthew-humphrey** [comment]
The lower PSU mount is completely unnecessary. The upper mounts are more than sufficient to suspend the PSU.

**Comment by Wiggleplum** [comment]
> 
> 
> The lower PSU mount is completely unnecessary. The upper mounts are more than sufficient to suspend the PSU.

Good to know. Thank you.

**Comment by gregsaun** [comment]
Fixed with latest 2.1.0-alpha1 release.
