### ISSUE TITLE
File Error in Slic3r PE

### ISSUE THREAD

**Issue by TimberRocket** [gregsaun/prusa_i3_bear_upgrade#84]
Slic3r PE isn't able to open any file of the full bear upgrade for the Prusa i3 Mk3.
Everyone shows an error and just closes. Is it a known issue?

**Comment by gregsaun** [comment]
Could you go on the main page:
https://github.com/gregsaun/prusa_i3_bear_upgrade

Click "Clone or download" and then "Download ZIP" and try again?

**Comment by TimberRocket** [comment]
Thank you for you fast respond :)
I'll try it as soon as i'm home.

**Comment by cggorman** [comment]
Are the v-slot frame parts the same for mk3 and mk3s?

**Comment by stahlfabrik** [comment]
Yes

**Comment by cggorman** [comment]
Thanks!  I'm brand new to github and 3d printing.  Just ordered a mk3s and trying to learn everything possible. Planning a full Bear as soon as I get the printer up and running properly.

**Comment by TimberRocket** [comment]
Gregsaun...
Tried downloading all files as copy (master) from the index page. Works great!
Seems that the files are somehow damaged while downloading them part by part
