### ISSUE TITLE
3D Printing 90 Degree Joining Plate Aluminum ?

### ISSUE THREAD

**Issue by Mayoogh** [gregsaun/prusa_i3_bear_upgrade#89]
Anyone tried 3D Printing the __90 Degree Joining Plate Aluminum__?

![GitHub Logo](http://cdn.shopify.com/s/files/1/0586/8617/products/lalum_large.jpg?v=1491608737)

**Comment by gregsaun** [comment]
I really don't recommend this, the plates is what is making a strong connection between the extrusions.
