### ISSUE TITLE
Cable management difficult without feet

### ISSUE THREAD

**Issue by gregsaun** [gregsaun/prusa_i3_bear_upgrade#9]
https://www.facebook.com/photo.php?fbid=1737186839633533&set=gm.828999217284561&type=3&theater&ifg=1

**Comment by FischOderAal** [comment]
I've got these under my Haribo
 http://s.aliexpress.com/RbIfUJnM

They are quite stiff though

**Comment by gregsaun** [comment]
Thanks FischOderAal

I will start with 3D printed rigid feet with the same shape/size as Prusa i3 MK2(s). Like this, you will be able to reuse your (home made) damping. I also have few ideas in mind but have to do some tests before
