### ISSUE TITLE
Distributing to Australia

### ISSUE THREAD

**Issue by v1nique** [gregsaun/prusa_i3_bear_upgrade#90]
Thank you for the wonderful mod and for you keeping it open source. Not sure if this is the right place to ask the question but, **are there any plans to distribute this in Australia**? Or should I seek out external companies to cut the parts to the specified dimensions.

**Comment by gregsaun** [comment]
I would love to have one but for now we have not been in contact with a store/distributor in Australia. Are you in contact with someone interested? Or are you interested?
