### ISSUE TITLE
More of a question with Alpha 2.1

### ISSUE THREAD

**Issue by evanquinnalaska** [gregsaun/prusa_i3_bear_upgrade#92]
Will 2.1 require new hardware that will deprecate the existing frame or will the frame stay as is and your just adding new printed part updates / enhancements? I ask because I have just ordered a 2.0 and see the 2.1 alpha and am worried that the frame equipment I will receive in 4 weeks may be out of date by the time I get it. Figured I would ask :)

**Comment by gregsaun** [comment]
You did well to ask for it. I am not planning to change anything to the frame. However, some printed parts and hardware (screws, nuts, washers) will change.
