### ISSUE TITLE
Download issues

### ISSUE THREAD

**Issue by noxidsoft** [gregsaun/prusa_i3_bear_upgrade#94]
Downloading these files to Windoze 10 they seem to break, can't open them, maybe to do with the long path? I have tried on several machines, though on the same static IP so it may just be me for now. Will try again tomorrow.

**Comment by gregsaun** [comment]
Go to the main page and click clone or Download and then Download Zip.

**Comment by noxidsoft** [comment]
Roger that, I grabbed it off of Thingiverse.
