### ISSUE TITLE
MK3 Full Frame - MK2 parts using Revision 2.1

### ISSUE THREAD

**Issue by aceycv8** [gregsaun/prusa_i3_bear_upgrade#99]
Hi - i think i know my own answer but want to double check before starting.

I've ordered a full MK3 frame and preparing all the STL's to print.
Which instructions do i use to build the frame from scratch? 
Do i use the MK3 instructions but use the "mk2s_on_mk3_parts_positions" to mount my parts?

Thank you

**Comment by gregsaun** [comment]
Hello, thank you for your order, hope you will like it :-)

You have to follow the instructions from the temporary assembly guide for all printed parts (parts position are describe in there). For the rest follow the instructions from Bear 2.0 Full Upgrade MK3 assembly (like for extrusions).

**Comment by gregsaun** [comment]
Bear 2.1 manual is here:
https://github.com/gregsaun/prusa_i3_bear_upgrade/tree/dev/manual

Bear 2.0 Full Upgrade MK3 is here:
https://github.com/gregsaun/prusa_i3_bear_upgrade/tree/master/full_upgrade/for_mk3/manual

**Comment by aceycv8** [comment]
Thankyou gregsaun - can't wait to see it in action!
